### ISSUE TITLE
а много их не будет верно?

### ISSUE THREAD

**Issue by nemoipaha** [SerhiiPlotnikov/2fa#13]
https://github.com/SerhiiPlotnikov/2fa/blob/b561cce71cc317545989deae9acd9798e7816605/app/Actions/Phones/GetDiallingCodes/GetDiallingCodesAction.php#L20

**Comment by SerhiiPlotnikov** [comment]
этого пока что точно не знаю. Но на данный момент их много. Почти все страны

**Comment by nemoipaha** [comment]
Может последних 100/200 вернуть? или сколько их всего?

**Comment by SerhiiPlotnikov** [comment]
Их всего около 200. Может заказчик скажет потом ограничить до 5. Сколько скажет оставлять, столько и оставлю
