### ISSUE TITLE
вы форсите юзеров на 2-х факторную всегда?

### ISSUE THREAD

**Issue by nemoipaha** [SerhiiPlotnikov/2fa#14]
https://github.com/SerhiiPlotnikov/2fa/blob/b561cce71cc317545989deae9acd9798e7816605/app/Actions/Phones/UpdateUserByPhone/UpdateUserByPhoneAction.php#L44

**Comment by SerhiiPlotnikov** [comment]
ну есть возможность ее отключить, но вообще да, выбираешь, через что будешь проводить аутентификацию и в этот момент идет регистрация в twillio
