### ISSUE TITLE
я бы добавил eager loading phoneNumber модели.

### ISSUE THREAD

**Issue by nemoipaha** [SerhiiPlotnikov/2fa#4]
https://github.com/SerhiiPlotnikov/2fa/blob/85d9ae955d204efe2e537ea72761a13515bc757c/app/User.php#L79

Проверку по идее тогда так можно упростить.
return null !== $this->phoneNumber;

Не совсем понял зачем эта проверка && $this->phoneNumber->phone_number !== null. Если же модель phoneNumber заатачена к юзеру. По бизнес логике поле phone_number тогда не может быть null?

**Comment by SerhiiPlotnikov** [comment]
Когда делаешь аутентификацию = disable, то ты можешь спокойно удалять номер и делать что хочешь с ним
