### ISSUE TITLE
нормас, но может переименовать как-то

### ISSUE THREAD

**Issue by nemoipaha** [SerhiiPlotnikov/2fa#7]
https://github.com/SerhiiPlotnikov/2fa/blob/85d9ae955d204efe2e537ea72761a13515bc757c/app/User.php#L90

usesForTwoFactorAuthentication(): bool

isrTwoFactorAuthEnabled(): bool

**Comment by SerhiiPlotnikov** [comment]
authy_id именно назначается юзеру, когда происходит регистрациия на twillio authy, ты потом можешь отключить аутиентификацию, но этот айдишник будет все еще привязан
