### ISSUE TITLE
а чего именно Throwable. Лучше ловить свой ексепшин аля BusinessException | DomainException

### ISSUE THREAD

**Issue by nemoipaha** [SerhiiPlotnikov/2fa#9]
https://github.com/SerhiiPlotnikov/2fa/blob/85d9ae955d204efe2e537ea72761a13515bc757c/app/Http/Controllers/TwoFactorSettingsController.php#L56

**Comment by SerhiiPlotnikov** [comment]
Метод обернут в транзакцию, а она брсоает 
  * @throws \Exception|\Throwable

**Comment by nemoipaha** [comment]
Транзакция бд?

**Comment by SerhiiPlotnikov** [comment]
ага
